version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis-srv
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander-web
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  consumer_one:
    container_name: go-consumer-one
    build: '.'
    environment:
      REDIS_HOST: redis
      STREAM: events
      GROUP: GroupOne
    depends_on:
      - redis
    restart: always

  consumer_two:
    container_name: go-consumer-two
    build: '.'
    environment:
      REDIS_HOST: redis
      STREAM: events
      GROUP: GroupTwo
    depends_on:
      - redis
    restart: always

  consumer_three:
    container_name: go-consumer-three
    build: '.'
    environment:
      REDIS_HOST: redis
      STREAM: events
      GROUP: GroupTwo
    depends_on:
      - redis
    restart: always

  producer_one:
    image: raychorn/buster_golang:02-20-21a
    container_name: go-producer-one
    build: '.'
    environment:
      REDIS_HOST: redis
      STREAM: events
    volumes:
      - ./producer/:/producer/
    entrypoint:
      - /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - redis
    restart: always